// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "annmenu.h"


/////////////////////////////////////////////////////////////////////////////
// CAnnMenu properties

short CAnnMenu::GetCount()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CAnnMenu::SetCount(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CAnnMenu operations

CString CAnnMenu::GetItemString(short iIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		iIndex);
	return result;
}

void CAnnMenu::SetItemString(short iIndex, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x5, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 iIndex, lpszNewValue);
}

long CAnnMenu::GetItemID(short iIndex)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		iIndex);
	return result;
}

void CAnnMenu::SetItemID(short iIndex, long nNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_I4;
	InvokeHelper(0x6, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 iIndex, nNewValue);
}

short CAnnMenu::GetItemType(short iIndex)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x7, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		iIndex);
	return result;
}

void CAnnMenu::SetItemType(short iIndex, short nNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x7, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 iIndex, nNewValue);
}

BOOL CAnnMenu::GetItemChecked(short iIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		iIndex);
	return result;
}

void CAnnMenu::SetItemChecked(short iIndex, BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_BOOL;
	InvokeHelper(0x8, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 iIndex, bNewValue);
}

BOOL CAnnMenu::GetItemEnabled(short iIndex)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x9, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		iIndex);
	return result;
}

void CAnnMenu::SetItemEnabled(short iIndex, BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_BOOL;
	InvokeHelper(0x9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 iIndex, bNewValue);
}

short CAnnMenu::DeleteItem(short iIndex)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		iIndex);
	return result;
}

short CAnnMenu::AddItem(LPCTSTR pszString, short iType, long nID, short iIndexBefore)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I4 VTS_I2;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		pszString, iType, nID, iIndexBefore);
	return result;
}

CAnnMenu CAnnMenu::GetSubMenu(short iIndex)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		iIndex);
	return CAnnMenu(pDispatch);
}
