#if !defined(AFX_LEADMARKER_H__98FE512D_7348_4383_88C4_389F7B07567F__INCLUDED_)
#define AFX_LEADMARKER_H__98FE512D_7348_4383_88C4_389F7B07567F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLEADMarker wrapper class

class CLEADMarker : public COleDispatchDriver
{
public:
	CLEADMarker() {}		// Calls COleDispatchDriver default constructor
	CLEADMarker(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLEADMarker(const CLEADMarker& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetType();
	void SetType(long);
	long GetSize();
	void SetSize(long);
	VARIANT GetData();
	void SetData(const VARIANT&);

// Operations
public:
	short Set(long lType, long lSize, const VARIANT& vData);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LEADMARKER_H__98FE512D_7348_4383_88C4_389F7B07567F__INCLUDED_)
