// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "leadmarker.h"


/////////////////////////////////////////////////////////////////////////////
// CLEADMarker properties

long CLEADMarker::GetType()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CLEADMarker::SetType(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CLEADMarker::GetSize()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CLEADMarker::SetSize(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

VARIANT CLEADMarker::GetData()
{
	VARIANT result;
	GetProperty(0x3, VT_VARIANT, (void*)&result);
	return result;
}

void CLEADMarker::SetData(const VARIANT& propVal)
{
	SetProperty(0x3, VT_VARIANT, &propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CLEADMarker operations

short CLEADMarker::Set(long lType, long lSize, const VARIANT& vData)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_VARIANT;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		lType, lSize, &vData);
	return result;
}
