// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "leadscrollinfo.h"


/////////////////////////////////////////////////////////////////////////////
// CLEADScrollInfo properties

long CLEADScrollInfo::GetMin()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CLEADScrollInfo::SetMin(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CLEADScrollInfo::GetMax()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CLEADScrollInfo::SetMax(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CLEADScrollInfo::GetPage()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CLEADScrollInfo::SetPage(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CLEADScrollInfo::GetLine()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CLEADScrollInfo::SetLine(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CLEADScrollInfo::GetPos()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CLEADScrollInfo::SetPos(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

BOOL CLEADScrollInfo::GetVisible()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CLEADScrollInfo::SetVisible(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

float CLEADScrollInfo::GetWidth()
{
	float result;
	GetProperty(0x7, VT_R4, (void*)&result);
	return result;
}

void CLEADScrollInfo::SetWidth(float propVal)
{
	SetProperty(0x7, VT_R4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CLEADScrollInfo operations
