//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace Reuters_with_Web_Service.com.reuters.rmb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RmdServiceSoapBinding", Namespace="http://rmb.reuters.com/rmd")]
    public partial class RmdService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChannelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback dropFieldGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFieldGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOnlineReportsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback setDefaultFieldGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPackagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback setFieldGroupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RmdService() {
            this.Url = global::Reuters_with_Web_Service.Properties.Settings.Default.Reuters_with_Web_Service_com_reuters_rmb_RmdService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getFieldsCompletedEventHandler getFieldsCompleted;
        
        /// <remarks/>
        public event getChannelsCompletedEventHandler getChannelsCompleted;
        
        /// <remarks/>
        public event dropFieldGroupCompletedEventHandler dropFieldGroupCompleted;
        
        /// <remarks/>
        public event getFieldGroupsCompletedEventHandler getFieldGroupsCompleted;
        
        /// <remarks/>
        public event getOnlineReportsCompletedEventHandler getOnlineReportsCompleted;
        
        /// <remarks/>
        public event getItemCompletedEventHandler getItemCompleted;
        
        /// <remarks/>
        public event getPackageCompletedEventHandler getPackageCompleted;
        
        /// <remarks/>
        public event setDefaultFieldGroupCompletedEventHandler setDefaultFieldGroupCompleted;
        
        /// <remarks/>
        public event getItemsCompletedEventHandler getItemsCompleted;
        
        /// <remarks/>
        public event getPackagesCompletedEventHandler getPackagesCompleted;
        
        /// <remarks/>
        public event setFieldGroupCompletedEventHandler setFieldGroupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fields getFields() {
            object[] results = this.Invoke("getFields", new object[0]);
            return ((fields)(results[0]));
        }
        
        /// <remarks/>
        public void getFieldsAsync() {
            this.getFieldsAsync(null);
        }
        
        /// <remarks/>
        public void getFieldsAsync(object userState) {
            if ((this.getFieldsOperationCompleted == null)) {
                this.getFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFieldsOperationCompleted);
            }
            this.InvokeAsync("getFields", new object[0], this.getFieldsOperationCompleted, userState);
        }
        
        private void OngetFieldsOperationCompleted(object arg) {
            if ((this.getFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFieldsCompleted(this, new getFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public availableChannels getChannels([System.Xml.Serialization.XmlElementAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] channel, [System.Xml.Serialization.XmlElementAttribute("channelCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] channelCategory) {
            object[] results = this.Invoke("getChannels", new object[] {
                        channel,
                        channelCategory});
            return ((availableChannels)(results[0]));
        }
        
        /// <remarks/>
        public void getChannelsAsync(string[] channel, string[] channelCategory) {
            this.getChannelsAsync(channel, channelCategory, null);
        }
        
        /// <remarks/>
        public void getChannelsAsync(string[] channel, string[] channelCategory, object userState) {
            if ((this.getChannelsOperationCompleted == null)) {
                this.getChannelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChannelsOperationCompleted);
            }
            this.InvokeAsync("getChannels", new object[] {
                        channel,
                        channelCategory}, this.getChannelsOperationCompleted, userState);
        }
        
        private void OngetChannelsOperationCompleted(object arg) {
            if ((this.getChannelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChannelsCompleted(this, new getChannelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fieldGroups dropFieldGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string name) {
            object[] results = this.Invoke("dropFieldGroup", new object[] {
                        name});
            return ((fieldGroups)(results[0]));
        }
        
        /// <remarks/>
        public void dropFieldGroupAsync(string name) {
            this.dropFieldGroupAsync(name, null);
        }
        
        /// <remarks/>
        public void dropFieldGroupAsync(string name, object userState) {
            if ((this.dropFieldGroupOperationCompleted == null)) {
                this.dropFieldGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OndropFieldGroupOperationCompleted);
            }
            this.InvokeAsync("dropFieldGroup", new object[] {
                        name}, this.dropFieldGroupOperationCompleted, userState);
        }
        
        private void OndropFieldGroupOperationCompleted(object arg) {
            if ((this.dropFieldGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dropFieldGroupCompleted(this, new dropFieldGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fieldGroups getFieldGroups([System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] name) {
            object[] results = this.Invoke("getFieldGroups", new object[] {
                        name});
            return ((fieldGroups)(results[0]));
        }
        
        /// <remarks/>
        public void getFieldGroupsAsync(string[] name) {
            this.getFieldGroupsAsync(name, null);
        }
        
        /// <remarks/>
        public void getFieldGroupsAsync(string[] name, object userState) {
            if ((this.getFieldGroupsOperationCompleted == null)) {
                this.getFieldGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFieldGroupsOperationCompleted);
            }
            this.InvokeAsync("getFieldGroups", new object[] {
                        name}, this.getFieldGroupsOperationCompleted, userState);
        }
        
        private void OngetFieldGroupsOperationCompleted(object arg) {
            if ((this.getFieldGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFieldGroupsCompleted(this, new getFieldGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public results getOnlineReports([System.Xml.Serialization.XmlElementAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] channel) {
            object[] results = this.Invoke("getOnlineReports", new object[] {
                        channel});
            return ((results)(results[0]));
        }
        
        /// <remarks/>
        public void getOnlineReportsAsync(string[] channel) {
            this.getOnlineReportsAsync(channel, null);
        }
        
        /// <remarks/>
        public void getOnlineReportsAsync(string[] channel, object userState) {
            if ((this.getOnlineReportsOperationCompleted == null)) {
                this.getOnlineReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOnlineReportsOperationCompleted);
            }
            this.InvokeAsync("getOnlineReports", new object[] {
                        channel}, this.getOnlineReportsOperationCompleted, userState);
        }
        
        private void OngetOnlineReportsOperationCompleted(object arg) {
            if ((this.getOnlineReportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOnlineReportsCompleted(this, new getOnlineReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getItem([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string itemId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string channel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string entityMarkup, [System.Xml.Serialization.XmlElementAttribute("entityMarkupField", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] entityMarkupField) {
            object[] results = this.Invoke("getItem", new object[] {
                        itemId,
                        channel,
                        entityMarkup,
                        entityMarkupField});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getItemAsync(string itemId, string channel, string entityMarkup, string[] entityMarkupField) {
            this.getItemAsync(itemId, channel, entityMarkup, entityMarkupField, null);
        }
        
        /// <remarks/>
        public void getItemAsync(string itemId, string channel, string entityMarkup, string[] entityMarkupField, object userState) {
            if ((this.getItemOperationCompleted == null)) {
                this.getItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetItemOperationCompleted);
            }
            this.InvokeAsync("getItem", new object[] {
                        itemId,
                        channel,
                        entityMarkup,
                        entityMarkupField}, this.getItemOperationCompleted, userState);
        }
        
        private void OngetItemOperationCompleted(object arg) {
            if ((this.getItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getItemCompleted(this, new getItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public results getPackage([System.Xml.Serialization.XmlElementAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string channel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fieldsRef, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fragmentLength, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool fragmentLengthSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool completeSentences, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool completeSentencesSpecified) {
            object[] results = this.Invoke("getPackage", new object[] {
                        id,
                        channel,
                        fieldsRef,
                        fragmentLength,
                        fragmentLengthSpecified,
                        completeSentences,
                        completeSentencesSpecified});
            return ((results)(results[0]));
        }
        
        /// <remarks/>
        public void getPackageAsync(string[] id, string channel, string fieldsRef, int fragmentLength, bool fragmentLengthSpecified, bool completeSentences, bool completeSentencesSpecified) {
            this.getPackageAsync(id, channel, fieldsRef, fragmentLength, fragmentLengthSpecified, completeSentences, completeSentencesSpecified, null);
        }
        
        /// <remarks/>
        public void getPackageAsync(string[] id, string channel, string fieldsRef, int fragmentLength, bool fragmentLengthSpecified, bool completeSentences, bool completeSentencesSpecified, object userState) {
            if ((this.getPackageOperationCompleted == null)) {
                this.getPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPackageOperationCompleted);
            }
            this.InvokeAsync("getPackage", new object[] {
                        id,
                        channel,
                        fieldsRef,
                        fragmentLength,
                        fragmentLengthSpecified,
                        completeSentences,
                        completeSentencesSpecified}, this.getPackageOperationCompleted, userState);
        }
        
        private void OngetPackageOperationCompleted(object arg) {
            if ((this.getPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPackageCompleted(this, new getPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fieldGroups setDefaultFieldGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string name) {
            object[] results = this.Invoke("setDefaultFieldGroup", new object[] {
                        name});
            return ((fieldGroups)(results[0]));
        }
        
        /// <remarks/>
        public void setDefaultFieldGroupAsync(string name) {
            this.setDefaultFieldGroupAsync(name, null);
        }
        
        /// <remarks/>
        public void setDefaultFieldGroupAsync(string name, object userState) {
            if ((this.setDefaultFieldGroupOperationCompleted == null)) {
                this.setDefaultFieldGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetDefaultFieldGroupOperationCompleted);
            }
            this.InvokeAsync("setDefaultFieldGroup", new object[] {
                        name}, this.setDefaultFieldGroupOperationCompleted, userState);
        }
        
        private void OnsetDefaultFieldGroupOperationCompleted(object arg) {
            if ((this.setDefaultFieldGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setDefaultFieldGroupCompleted(this, new setDefaultFieldGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public results getItems([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dateRange, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string maxAge, [System.Xml.Serialization.XmlElementAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] channel, [System.Xml.Serialization.XmlElementAttribute("mediaType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] mediaType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int limit, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool limitSpecified, [System.Xml.Serialization.XmlElementAttribute("channelCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] channelCategory, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fieldsRef, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fragmentLength, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool fragmentLengthSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool completeSentences, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool completeSentencesSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pollToken) {
            object[] results = this.Invoke("getItems", new object[] {
                        dateRange,
                        maxAge,
                        channel,
                        mediaType,
                        limit,
                        limitSpecified,
                        channelCategory,
                        fieldsRef,
                        fragmentLength,
                        fragmentLengthSpecified,
                        completeSentences,
                        completeSentencesSpecified,
                        pollToken});
            return ((results)(results[0]));
        }
        
        /// <remarks/>
        public void getItemsAsync(string dateRange, string maxAge, string[] channel, string[] mediaType, int limit, bool limitSpecified, string[] channelCategory, string fieldsRef, int fragmentLength, bool fragmentLengthSpecified, bool completeSentences, bool completeSentencesSpecified, string pollToken) {
            this.getItemsAsync(dateRange, maxAge, channel, mediaType, limit, limitSpecified, channelCategory, fieldsRef, fragmentLength, fragmentLengthSpecified, completeSentences, completeSentencesSpecified, pollToken, null);
        }
        
        /// <remarks/>
        public void getItemsAsync(string dateRange, string maxAge, string[] channel, string[] mediaType, int limit, bool limitSpecified, string[] channelCategory, string fieldsRef, int fragmentLength, bool fragmentLengthSpecified, bool completeSentences, bool completeSentencesSpecified, string pollToken, object userState) {
            if ((this.getItemsOperationCompleted == null)) {
                this.getItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetItemsOperationCompleted);
            }
            this.InvokeAsync("getItems", new object[] {
                        dateRange,
                        maxAge,
                        channel,
                        mediaType,
                        limit,
                        limitSpecified,
                        channelCategory,
                        fieldsRef,
                        fragmentLength,
                        fragmentLengthSpecified,
                        completeSentences,
                        completeSentencesSpecified,
                        pollToken}, this.getItemsOperationCompleted, userState);
        }
        
        private void OngetItemsOperationCompleted(object arg) {
            if ((this.getItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getItemsCompleted(this, new getItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public results getPackages([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string channel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool useSNEP, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool useSNEPSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dateRange, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string maxAge, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int limit, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool limitSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fieldsRef, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fragmentLength, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool fragmentLengthSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool completeSentences, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool completeSentencesSpecified) {
            object[] results = this.Invoke("getPackages", new object[] {
                        channel,
                        useSNEP,
                        useSNEPSpecified,
                        dateRange,
                        maxAge,
                        limit,
                        limitSpecified,
                        fieldsRef,
                        fragmentLength,
                        fragmentLengthSpecified,
                        completeSentences,
                        completeSentencesSpecified});
            return ((results)(results[0]));
        }
        
        /// <remarks/>
        public void getPackagesAsync(string channel, bool useSNEP, bool useSNEPSpecified, string dateRange, string maxAge, int limit, bool limitSpecified, string fieldsRef, int fragmentLength, bool fragmentLengthSpecified, bool completeSentences, bool completeSentencesSpecified) {
            this.getPackagesAsync(channel, useSNEP, useSNEPSpecified, dateRange, maxAge, limit, limitSpecified, fieldsRef, fragmentLength, fragmentLengthSpecified, completeSentences, completeSentencesSpecified, null);
        }
        
        /// <remarks/>
        public void getPackagesAsync(string channel, bool useSNEP, bool useSNEPSpecified, string dateRange, string maxAge, int limit, bool limitSpecified, string fieldsRef, int fragmentLength, bool fragmentLengthSpecified, bool completeSentences, bool completeSentencesSpecified, object userState) {
            if ((this.getPackagesOperationCompleted == null)) {
                this.getPackagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPackagesOperationCompleted);
            }
            this.InvokeAsync("getPackages", new object[] {
                        channel,
                        useSNEP,
                        useSNEPSpecified,
                        dateRange,
                        maxAge,
                        limit,
                        limitSpecified,
                        fieldsRef,
                        fragmentLength,
                        fragmentLengthSpecified,
                        completeSentences,
                        completeSentencesSpecified}, this.getPackagesOperationCompleted, userState);
        }
        
        private void OngetPackagesOperationCompleted(object arg) {
            if ((this.getPackagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPackagesCompleted(this, new getPackagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rmb.reuters.com/rmd", ResponseNamespace="http://rmb.reuters.com/rmd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fieldGroups setFieldGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string name, [System.Xml.Serialization.XmlElementAttribute("field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] field) {
            object[] results = this.Invoke("setFieldGroup", new object[] {
                        name,
                        field});
            return ((fieldGroups)(results[0]));
        }
        
        /// <remarks/>
        public void setFieldGroupAsync(string name, string[] field) {
            this.setFieldGroupAsync(name, field, null);
        }
        
        /// <remarks/>
        public void setFieldGroupAsync(string name, string[] field, object userState) {
            if ((this.setFieldGroupOperationCompleted == null)) {
                this.setFieldGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetFieldGroupOperationCompleted);
            }
            this.InvokeAsync("setFieldGroup", new object[] {
                        name,
                        field}, this.setFieldGroupOperationCompleted, userState);
        }
        
        private void OnsetFieldGroupOperationCompleted(object arg) {
            if ((this.setFieldGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setFieldGroupCompleted(this, new setFieldGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class fields {
        
        private statusBean statusField;
        
        private fieldWrapper[] fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public statusBean status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fieldWrapper[] field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class statusBean {
        
        private errorBean[] errorField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public errorBean[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class errorBean {
        
        private int codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class percent {
        
        private string nameField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class supplementalLinks {
        
        private result[] linkField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public result[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class result {
        
        private string idField;
        
        private string guidField;
        
        private int versionField;
        
        private bool versionFieldSpecified;
        
        private string urlField;
        
        private System.DateTime dateCreatedField;
        
        private bool dateCreatedFieldSpecified;
        
        private string slugField;
        
        private string authorField;
        
        private string sourceField;
        
        private string languageField;
        
        private string headlineField;
        
        private string mediaTypeField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        private string geographyField;
        
        private string previewUrlField;
        
        private int durationField;
        
        private bool durationFieldSpecified;
        
        private long sizeField;
        
        private bool sizeFieldSpecified;
        
        private string dimensionsField;
        
        private string fragmentField;
        
        private string[] topicField;
        
        private string[] genreField;
        
        private string[] channelField;
        
        private string editNumberField;
        
        private bool remoteContentCompleteField;
        
        private bool remoteContentCompleteFieldSpecified;
        
        private float scoreField;
        
        private bool scoreFieldSpecified;
        
        private result[] mainLinksField;
        
        private supplementalLinks[] supplementalLinksField;
        
        private string[] additionalPackagesField;
        
        private string[] labelField;
        
        private int supplementalTextLinkCountField;
        
        private bool supplementalTextLinkCountFieldSpecified;
        
        private int supplementalImageLinkCountField;
        
        private bool supplementalImageLinkCountFieldSpecified;
        
        private int supplementalVideoLinkCountField;
        
        private bool supplementalVideoLinkCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreatedSpecified {
            get {
                return this.dateCreatedFieldSpecified;
            }
            set {
                this.dateCreatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string slug {
            get {
                return this.slugField;
            }
            set {
                this.slugField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string headline {
            get {
                return this.headlineField;
            }
            set {
                this.headlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string geography {
            get {
                return this.geographyField;
            }
            set {
                this.geographyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string previewUrl {
            get {
                return this.previewUrlField;
            }
            set {
                this.previewUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified {
            get {
                return this.durationFieldSpecified;
            }
            set {
                this.durationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fragment {
            get {
                return this.fragmentField;
            }
            set {
                this.fragmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("topic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] topic {
            get {
                return this.topicField;
            }
            set {
                this.topicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("genre", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string editNumber {
            get {
                return this.editNumberField;
            }
            set {
                this.editNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool remoteContentComplete {
            get {
                return this.remoteContentCompleteField;
            }
            set {
                this.remoteContentCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool remoteContentCompleteSpecified {
            get {
                return this.remoteContentCompleteFieldSpecified;
            }
            set {
                this.remoteContentCompleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("link", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public result[] mainLinks {
            get {
                return this.mainLinksField;
            }
            set {
                this.mainLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supplementalLinks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public supplementalLinks[] supplementalLinks {
            get {
                return this.supplementalLinksField;
            }
            set {
                this.supplementalLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] additionalPackages {
            get {
                return this.additionalPackagesField;
            }
            set {
                this.additionalPackagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("label", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int supplementalTextLinkCount {
            get {
                return this.supplementalTextLinkCountField;
            }
            set {
                this.supplementalTextLinkCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool supplementalTextLinkCountSpecified {
            get {
                return this.supplementalTextLinkCountFieldSpecified;
            }
            set {
                this.supplementalTextLinkCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int supplementalImageLinkCount {
            get {
                return this.supplementalImageLinkCountField;
            }
            set {
                this.supplementalImageLinkCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool supplementalImageLinkCountSpecified {
            get {
                return this.supplementalImageLinkCountFieldSpecified;
            }
            set {
                this.supplementalImageLinkCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int supplementalVideoLinkCount {
            get {
                return this.supplementalVideoLinkCountField;
            }
            set {
                this.supplementalVideoLinkCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool supplementalVideoLinkCountSpecified {
            get {
                return this.supplementalVideoLinkCountFieldSpecified;
            }
            set {
                this.supplementalVideoLinkCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class results {
        
        private result[] resultField;
        
        private long numFoundField;
        
        private bool numFoundFieldSpecified;
        
        private int sizeField;
        
        private bool sizeFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        private percent[] mediaTypeBreakdownField;
        
        private bool hasPackagesField;
        
        private bool hasPackagesFieldSpecified;
        
        private string pollTokenField;
        
        private statusBean statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public result[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long numFound {
            get {
                return this.numFoundField;
            }
            set {
                this.numFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numFoundSpecified {
            get {
                return this.numFoundFieldSpecified;
            }
            set {
                this.numFoundFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public percent[] mediaTypeBreakdown {
            get {
                return this.mediaTypeBreakdownField;
            }
            set {
                this.mediaTypeBreakdownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool hasPackages {
            get {
                return this.hasPackagesField;
            }
            set {
                this.hasPackagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasPackagesSpecified {
            get {
                return this.hasPackagesFieldSpecified;
            }
            set {
                this.hasPackagesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pollToken {
            get {
                return this.pollTokenField;
            }
            set {
                this.pollTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public statusBean status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class fieldGroupWrapper {
        
        private string nameField;
        
        private bool updatableField;
        
        private bool defaultForQueryField;
        
        private fieldWrapper[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool updatable {
            get {
                return this.updatableField;
            }
            set {
                this.updatableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool defaultForQuery {
            get {
                return this.defaultForQueryField;
            }
            set {
                this.defaultForQueryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public fieldWrapper[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class fieldWrapper {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class fieldGroups {
        
        private statusBean statusField;
        
        private fieldGroupWrapper[] fieldGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public statusBean status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fieldGroupWrapper[] fieldGroup {
            get {
                return this.fieldGroupField;
            }
            set {
                this.fieldGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class channelCategory {
        
        private channelCategory categoryField;
        
        private string descriptionField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public channelCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class channelInformation {
        
        private string descriptionField;
        
        private string aliasField;
        
        private System.DateTime lastUpdateField;
        
        private bool lastUpdateFieldSpecified;
        
        private channelCategory categoryField;
        
        private string[] availableContentProfilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdateSpecified {
            get {
                return this.lastUpdateFieldSpecified;
            }
            set {
                this.lastUpdateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public channelCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("profile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] availableContentProfiles {
            get {
                return this.availableContentProfilesField;
            }
            set {
                this.availableContentProfilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmb.reuters.com/rmd")]
    public partial class availableChannels {
        
        private channelInformation[] channelInformationField;
        
        private statusBean statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("channelInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public channelInformation[] channelInformation {
            get {
                return this.channelInformationField;
            }
            set {
                this.channelInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public statusBean status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getFieldsCompletedEventHandler(object sender, getFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fields Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fields)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getChannelsCompletedEventHandler(object sender, getChannelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChannelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChannelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public availableChannels Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((availableChannels)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void dropFieldGroupCompletedEventHandler(object sender, dropFieldGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dropFieldGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dropFieldGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fieldGroups Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fieldGroups)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getFieldGroupsCompletedEventHandler(object sender, getFieldGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFieldGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFieldGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fieldGroups Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fieldGroups)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getOnlineReportsCompletedEventHandler(object sender, getOnlineReportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOnlineReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOnlineReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public results Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((results)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getItemCompletedEventHandler(object sender, getItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPackageCompletedEventHandler(object sender, getPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public results Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((results)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setDefaultFieldGroupCompletedEventHandler(object sender, setDefaultFieldGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setDefaultFieldGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setDefaultFieldGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fieldGroups Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fieldGroups)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getItemsCompletedEventHandler(object sender, getItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public results Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((results)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPackagesCompletedEventHandler(object sender, getPackagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPackagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPackagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public results Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((results)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setFieldGroupCompletedEventHandler(object sender, setFieldGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setFieldGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setFieldGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fieldGroups Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fieldGroups)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591